//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "binding")]
pub struct Model {
    pub aid: Option<i64>,
    pub bid: Option<i64>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub platform: String,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
