//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub platform: String,
    pub flag: Option<i64>,
    pub assignee: Option<String>,
    #[sea_orm(column_name = "guildId")]
    pub guild_id: Option<String>,
    pub locales: Option<Vec<String>>,
    pub permissions: Option<Vec<String>>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
