//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cp_handle_v1")]
pub struct Model {
    pub created_time: DateTimeWithTimeZone,
    pub deleted: i16,
    pub deleted_time: Option<DateTimeWithTimeZone>,
    pub deleted_reason: i16,
    #[sea_orm(primary_key)]
    pub handle_id: i64,
    pub handle_type: i16,
    #[sea_orm(unique)]
    pub handle: String,
    pub cpid: i64,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
