//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cp_v1")]
pub struct Model {
    pub created_time: DateTimeWithTimeZone,
    pub deleted: i16,
    pub deleted_time: Option<DateTimeWithTimeZone>,
    pub deleted_reason: i16,
    #[sea_orm(primary_key)]
    pub cpid: i64,
    pub cp_version: i16,
    pub creator: i64,
    pub owner: i64,
    pub data_full_mode: i16,
    #[sea_orm(column_type = "Text")]
    pub data_full: String,
    #[sea_orm(column_type = "Text")]
    pub data_summary: String,
    pub platform: i16,
    pub cpssr_version: i16,
    pub cpssr_niaid: Option<i64>,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
