//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub permissions: Option<Vec<String>>,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
