//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "niassets_v1")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub niaid: i64,
    pub r#type: i16,
    #[sea_orm(unique)]
    pub handle: String,
    pub size: i32,
    #[sea_orm(column_type = "Text")]
    pub filename: String,
    pub mime: String,
    pub thumbhash: Option<String>,
    pub width: i32,
    pub height: i32,
    pub tg_file_id: Option<String>,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
