//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "niassets_rc_v1")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub niaid: i64,
    pub ref_type: i16,
    pub ref_id: i64,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
