//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::binding::Entity as Binding;
pub use super::channel::Entity as Channel;
pub use super::cp_handle_v1::Entity as CpHandleV1;
pub use super::cp_v1::Entity as CpV1;
pub use super::group::Entity as Group;
pub use super::niassets_rc_v1::Entity as NiassetsRcV1;
pub use super::niassets_v1::Entity as NiassetsV1;
pub use super::perm_track::Entity as PermTrack;
pub use super::user::Entity as User;
