//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: Option<String>,
    pub flag: Option<i64>,
    pub authority: Option<i32>,
    pub locales: Option<Vec<String>>,
    pub permissions: Option<Vec<String>>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_name = "nekoilAuthority")]
    pub nekoil_authority: Option<i16>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub usage: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub timers: Option<Json>,
    #[sea_orm(column_name = "_pg_mtime")]
    pub pg_mtime: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
