approvedGitRepositories:
  - "**"

enableScripts: true

enableTips: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.yarnpkg.com"

npmRegistryServer: "https://registry.npmmirror.com"
